### ISSUE TITLE
Play video from azure storage blob/readstream

### ISSUE THREAD

**Issue by hans0low** [react-native-community/react-native-video#1209]
### Current behavior
I get the error AVFoundationErrorDomain.

The video works fine when pulled up in firefox/safari and also in our website video tag. Mobile side is the only place where the video stream doesn't seem to play. Either way we try to fix it we always get the error above (in HTTPS and HTTP).

Any suggestions would be extremely helpful.

### Reproduction steps
Have an mp4 file in azure blob storage
Access the blob using azure-storage npm package
Call function getBlobToStream
Using URL created to read video file

### Platform
Which player are you experiencing the problem on:
* iOS

### Video sample
 https://nw-scout.azurewebsites.net/videos/e9b315b0-a17a-11e8-a2bc-b16050baa314.mp4

**Comment by cobarx** [comment]
When I attempt to pull that URL up in a browser, I get a binary byte stream rather than it loading in the browser video player. That probably means the web server isn't setting a mimetype for the file. That needs to be set.

Also, it may be that the server doesn't support grabbing byte ranges. When dealing with video, the player needs to be able to request different parts of the file so that when you seek it only gets the part it needs. I don't know if the server supports that, but you should check.

I would see if there is a CDN feature for doing video hosted off Azure. For AWS, Amazon has a service called CloudFront that grabs the files out of S3 storage and serves them to the client and handles all the quirks for S3. See if something similar exists for Azure.
